"""empty message

Revision ID: df935d745af5
Revises: 63f2d2be5216
Create Date: 2020-09-18 18:00:36.395976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df935d745af5'
down_revision = '63f2d2be5216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in', sa.Column('usuário_responsável', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_in', 'usuário_responsável')
    # ### end Alembic commands ###
